//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Log
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesLog : DbContext
    {
        public EntitiesLog()
            : base("name=EntitiesLog")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLog> AccessLogs { get; set; }
        public virtual DbSet<SmsLog> SmsLogs { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<CandidateByPassLog> CandidateByPassLogs { get; set; }
        public virtual DbSet<CandidateAdmitCardDownloadClickLog> CandidateAdmitCardDownloadClickLogs { get; set; }
        public virtual DbSet<DataLog> DataLogs { get; set; }
    }
}
