//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateByPassLog
    {
        public int ID { get; set; }
        public Nullable<long> SystemUserID { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<long> CandidatePaymentID { get; set; }
        public string Page { get; set; }
        public Nullable<System.DateTime> CandidateApplyDate { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Attribute6 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
