//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Log
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public long ID { get; set; }
        public string SentBy { get; set; }
        public string Page { get; set; }
        public Nullable<long> StudentId { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string ToName { get; set; }
        public string FromName { get; set; }
        public string MessageBody { get; set; }
        public string MessageSubject { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
    }
}
