//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public long ID { get; set; }
        public long CandidateID { get; set; }
        public Nullable<bool> IsEnrolled { get; set; }
        public string CurrentStudentId { get; set; }
        public Nullable<bool> IsCurrentlyEnrolledElsewhere { get; set; }
        public string CurrentlyEnrolledInstitute { get; set; }
        public Nullable<decimal> CandidateIncome { get; set; }
        public Nullable<decimal> FatherAnnualIncome { get; set; }
        public Nullable<decimal> MotherAnnualIncome { get; set; }
        public Nullable<decimal> GuardianAnnualIncome { get; set; }
        public Nullable<bool> IsDismissedBefore { get; set; }
        public string DismissalStatement { get; set; }
        public Nullable<bool> IsScholarshipAwarded { get; set; }
        public Nullable<long> ScholarshipWaiverID { get; set; }
        public string ScholarshipAwardDetails { get; set; }
        public Nullable<bool> IsResidenceRequired { get; set; }
        public Nullable<bool> IsDirectAdmission { get; set; }
        public Nullable<bool> IsPreMath { get; set; }
        public Nullable<bool> IsPreEnglish { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public Nullable<bool> IsFinalSubmit { get; set; }
        public Nullable<bool> IsForeignStudent { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public string TransferDetails { get; set; }
        public string Remarks { get; set; }
        public string AttributeString1 { get; set; }
        public string AttributeString2 { get; set; }
        public Nullable<int> AttributeInt1 { get; set; }
        public Nullable<int> AttributeInt2 { get; set; }
        public Nullable<decimal> AttributeDec1 { get; set; }
        public Nullable<decimal> AttributeDec2 { get; set; }
        public Nullable<bool> AttributeBool1 { get; set; }
        public Nullable<bool> AttributeBool2 { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string PassportNumber { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
        public virtual ScholarshipWaiver ScholarshipWaiver { get; set; }
    }
}
