//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressDetail()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public long ID { get; set; }
        public string AddressLine { get; set; }
        public string RoadNo { get; set; }
        public string RoadName { get; set; }
        public string HouseNo { get; set; }
        public string HouseName { get; set; }
        public string SectionBlockNo { get; set; }
        public string Area { get; set; }
        public string Village { get; set; }
        public string Thana { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Upazila { get; set; }
        public string PostCode { get; set; }
        public string PostOffice { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Others { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
