//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionSetupOtherProgram
    {
        public int ID { get; set; }
        public Nullable<int> ProgramTypeId { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string ProgramShortName { get; set; }
        public string ProgramDetailsName { get; set; }
        public string FileURL { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SerialNo { get; set; }
    }
}
