//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasicInfo()
        {
            this.AdditionalInfoes = new HashSet<AdditionalInfo>();
            this.Addresses = new HashSet<Address>();
            this.CandidateFormSls = new HashSet<CandidateFormSl>();
            this.DiscountDetails = new HashSet<DiscountDetail>();
            this.Documents = new HashSet<Document>();
            this.Exams = new HashSet<Exam>();
            this.ExtraCurricularActivities = new HashSet<ExtraCurricularActivity>();
            this.FinancialGuarantorInfoes = new HashSet<FinancialGuarantorInfo>();
            this.References = new HashSet<Reference>();
            this.Relations = new HashSet<Relation>();
            this.SchoolMarks = new HashSet<SchoolMark>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.ProgramPriorities = new HashSet<ProgramPriority>();
            this.CandidatePayments = new HashSet<CandidatePayment>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string FullName_BEN { get; set; }
        public string Mobile { get; set; }
        public string PhoneResidence { get; set; }
        public string EmergencyPhone { get; set; }
        public string GuardianPhone { get; set; }
        public string SMSPhone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string BirthRegistrationNo { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string NationalIdNumber { get; set; }
        public Nullable<int> MotherTongueID { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> QuotaID { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public long CandidateUserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> UniqueIdentifier { get; set; }
        public string Remarks { get; set; }
        public string AttributeStr1 { get; set; }
        public string AttributeStr2 { get; set; }
        public Nullable<int> AttributeInt1 { get; set; }
        public Nullable<int> AttributeInt2 { get; set; }
        public Nullable<decimal> AttributeDec { get; set; }
        public Nullable<bool> AttributeBool { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Quota Quota { get; set; }
        public virtual Religion Religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalInfo> AdditionalInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateFormSl> CandidateFormSls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountDetail> DiscountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraCurricularActivity> ExtraCurricularActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialGuarantorInfo> FinancialGuarantorInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation> Relations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolMark> SchoolMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPriority> ProgramPriorities { get; set; }
        public virtual CandidateUser CandidateUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePayment> CandidatePayments { get; set; }
    }
}
