//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkAdmitCardGenerateLOG
    {
        public int ID { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<long> AdmissionUnitID { get; set; }
        public Nullable<int> AcaCalID { get; set; }
        public Nullable<long> FormSL { get; set; }
        public string TestRoll { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsGenerated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
