//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateFormSl
    {
        public long ID { get; set; }
        public long CandidateID { get; set; }
        public long AdmissionSetupID { get; set; }
        public Nullable<int> AcaCalID { get; set; }
        public long FormSerial { get; set; }
        public long CandidatePaymentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
        public virtual AdmissionSetup AdmissionSetup { get; set; }
        public virtual CandidatePayment CandidatePayment { get; set; }
    }
}
