//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateFacultyWiseDistrictSeat
    {
        public long ID { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> AdmissionSetupId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Remarks { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
