//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidatePayment()
        {
            this.CandidateFormSls = new HashSet<CandidateFormSl>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<long> PaymentId { get; set; }
        public Nullable<int> AcaCalID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateFormSl> CandidateFormSls { get; set; }
    }
}
