//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountDetail
    {
        public long ID { get; set; }
        public long CandidateID { get; set; }
        public long DiscountID { get; set; }
        public Nullable<bool> IsActiveDiscount { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
