//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictSeatLimit
    {
        public int ID { get; set; }
        public Nullable<long> AdmissionUnitId { get; set; }
        public Nullable<int> AcaCalId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> SeatLimit { get; set; }
        public Nullable<int> SeatFillup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
