//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignCandidatePaymentInformation
    {
        public int ID { get; set; }
        public Nullable<long> ProgramPriorityId { get; set; }
        public Nullable<long> FormSerialId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string BankName { get; set; }
        public string TransactionId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Attribute1 { get; set; }
        public Nullable<int> Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
