//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public long ID { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeDetails { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string EID { get; set; }
        public Nullable<int> NoticeType { get; set; }
        public string Remarks { get; set; }
    }
}
