//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostgraduateDiplomaRelationDetail
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsGuardian { get; set; }
        public string RelationWithGuardian { get; set; }
        public string Occupation { get; set; }
        public string Organization { get; set; }
        public string OrgAddress { get; set; }
        public string Designation { get; set; }
        public string Mobile { get; set; }
        public string PhoneResidence { get; set; }
        public string PhoneOffice { get; set; }
        public string Email { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string NationalIdNumber { get; set; }
        public string MailingAddress { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Upazila { get; set; }
        public Nullable<bool> IsLate { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
