//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostgraduateDiplomaCandidateUser
    {
        public long ID { get; set; }
        public string UsernameLoginId { get; set; }
        public string Password { get; set; }
        public string ConfirmationToken { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> LastPasswordFailureDate { get; set; }
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
        public string PasswordVerificationToken { get; set; }
        public Nullable<System.DateTime> PasswordVerificationTokenExpirationDate { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<bool> IsSentSms { get; set; }
        public Nullable<bool> IsSentEmail { get; set; }
        public Nullable<long> RoleID { get; set; }
        public Nullable<long> AdmissionSetupID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
