//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramPriority
    {
        public long ID { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<long> AdmissionUnitID { get; set; }
        public Nullable<long> AdmissionUnitProgramID { get; set; }
        public Nullable<long> AdmissionSetupID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> AcaCalID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
    
        public virtual BasicInfo BasicInfo { get; set; }
        public virtual AdmissionSetup AdmissionSetup { get; set; }
        public virtual AdmissionUnit AdmissionUnit { get; set; }
        public virtual AdmissionUnitProgram AdmissionUnitProgram { get; set; }
    }
}
