//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleTalkBoardResult
    {
        public long ID { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<int> AcaCalId { get; set; }
        public string SSCBoardResultInJson { get; set; }
        public Nullable<bool> IsVerifiedSSC { get; set; }
        public string HSCBoardResultInJson { get; set; }
        public Nullable<bool> IsVerifiedHSC { get; set; }
    }
}
