//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitProgramDetail
    {
        public long ID { get; set; }
        public long AdmissionUnitID { get; set; }
        public int EducationCategoryID { get; set; }
        public string Intake { get; set; }
        public string ClassStart { get; set; }
        public string MethodOfApplication { get; set; }
        public string NoOfSeats { get; set; }
        public Nullable<int> DurationYear { get; set; }
        public Nullable<int> DurationSemester { get; set; }
        public Nullable<int> TotalCredit { get; set; }
        public Nullable<decimal> TotalCourseFee { get; set; }
        public string AdmissionEligibility { get; set; }
        public string AdmissionTestSyllabus { get; set; }
        public string AdFileUrl { get; set; }
        public string AdmissionFormUrl { get; set; }
        public string Weightage { get; set; }
        public string ExamType { get; set; }
        public string ContactInfo { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual EducationCategory EducationCategory { get; set; }
        public virtual AdmissionUnit AdmissionUnit { get; set; }
    }
}
