//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLProperty
    {
        public long ID { get; set; }
        public Nullable<int> URLType { get; set; }
        public string URLName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public Nullable<int> AttributeInt1 { get; set; }
        public Nullable<int> AttributeInt2 { get; set; }
        public Nullable<int> AttributeInt3 { get; set; }
        public Nullable<decimal> AttributeDec1 { get; set; }
        public Nullable<decimal> AttributeDec2 { get; set; }
        public Nullable<decimal> AttributeDec3 { get; set; }
    }
}
