//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VivaSelectionSetup
    {
        public long ID { get; set; }
        public Nullable<int> AdmissionUnitID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<int> General { get; set; }
        public Nullable<int> Military { get; set; }
        public Nullable<int> FreedomFighter { get; set; }
        public Nullable<int> Tribal { get; set; }
        public Nullable<int> SittingMember { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
