//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_UCAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramType
    {
        public int ProgramTypeID { get; set; }
        public string TypeDescription { get; set; }
    }
}
